# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('deviceID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterParticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('orp', models.FloatField(blank=True, null=True)),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('geoLocation', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
